server {
    listen 80;
    listen [::]:80;
    server_name nexgate.space www.nexgate.space;

    root /var/www/nexgate.space;
    index index.html;

    location = /index.html {
        return 301 /;
    }

    location ~ ^/(.+)\.html$ {
        return 301 /$1;
    }

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}
